name: Build and Test
on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'Protobuf/**'
      - '**/dependabot.yml'
      
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'Protobuf/**'
      - '**/dependabot.yml'

  workflow_dispatch:

jobs:
  Build-and-Test:
    runs-on: macos-14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build
        run: swift build

      - name: Test
        run: swift test
